language: ruby
rvm:
- 2.3.1

install: gem install html-proofer
script: htmlproofer ./index.php

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
